version: "2"
services:
  # Set up a deployer
  deploy:
    build: .
    environment:
      - WAIT_FOR=/test/main.yaml
      - WHEN_DONE=/test/done
      - DEPLOY_TEMPLATE=/test/main.yaml
      - DEBUG=true
      - PARAM_MyTestParam=testing
      # - PACKAGE_BUCKET=
      # - AWS_DEFAULT_REGION=
      # - AWS_SECRET_ACCESS_KEY=
      # - AWS_ACCESS_KEY_ID=
    volumes:
      - data-volume:/test
  # Testing script
  sut:
    depends_on:
      - deploy
    build: test/
    command: /setup/test.sh
    volumes:
      - data-volume:/test

volumes:
  data-volume: ~