#!/bin/bash

if echo $DOCKER_TAG | egrep "^[0-9]+\.[0-9]+\.[0-9]+"; then
    MAJOR=$(echo $DOCKER_TAG | cut -d. -f1)
    MINOR=$(echo $DOCKER_TAG | cut -d. -f1-2)
    PATCH=$(echo $DOCKER_TAG)

    echo "Tagging major: $MAJOR"
    docker tag "$IMAGE_NAME" "$DOCKER_REPO:$MAJOR"
    docker push "$DOCKER_REPO:$MAJOR"
    echo "Tagging minor: $MINOR"
    docker tag "$IMAGE_NAME" "$DOCKER_REPO:$MINOR"
    docker push "$DOCKER_REPO:$MAJOR"
    echo "Tagging patch: $PATCH"
    docker tag "$IMAGE_NAME" "$DOCKER_REPO:$PATCH"
    docker push "$DOCKER_REPO:$MAJOR"
else
    echo "Not tagging $DOCKER_TAG"
fi